version: "3.8"
services:
  tickerbell-a:
    container_name: tickerbell-a
    image: ${DOCKERHUB_USERNAME}/tickerbell
    environment:
      - DB_ENDPOINT=${DB_ENDPOINT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - SMS_ACCESS_KEY=${SMS_ACCESS_KEY}
      - SMS_SECRET_KEY=${SMS_SECRET_KEY}
      - SMS_SERVICE_ID=${SMS_SERVICE_ID}
      - SMS_SENDER_PHONE=${SMS_SENDER_PHONE}
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - KAKAO_REDIRECT=${KAKAO_REDIRECT}
      - MAP_API_KEY_ID=${MAP_API_KEY_ID}
      - MAP_API_KEY=${MAP_API_KEY}
    ports:
      - "8080:8080"
    restart: always
networks:
  default:
    external:
      name: tickerbellnet

