spring:
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
