app:
  auth:
    secret-key: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    s3:
      bucket: tickerbell-image
    stack.auto: false #기본 cloudFormation 구성 시작 사용 x
    region:
      static: ap-northeast-2

naver-cloud-sms:
  accessKey: ${SMS_ACCESS_KEY}
  secretKey: ${SMS_SECRET_KEY}
  serviceId: ${SMS_SERVICE_ID}
  senderPhone: ${SMS_SENDER_PHONE}

naver-cloud-map:
  api-key-id: ${MAP_API_KEY_ID}
  api-key: ${MAP_API_KEY}