spring:
  profiles:
    active: local
    include: connection, oauth2, app

---
spring:
  profiles:
    active: prod
    include: connection2, oauth2, app


# java -jar tickerBell-0.0.1-SNAPSHOT.jar --spring.profiles.active={local or prod} 로 명령어 실행