spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tickerbell-db.cgtvzaoa0zox.ap-northeast-2.rds.amazonaws.com:3306/tickerBellDB
    username: admin
    password: tickerBell1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
