spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT}
            client-authentication-method: POST
            authorization-grant-type: authorization_code # 웹 애플리케이션 또는 모바일 앱과 같은 안전한 환경에서 사용
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
