spring:
  profiles:
    active: local
    include: connection, oauth2

app:
  auth:
    secret-key: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    s3:
      bucket: tickerbell-image
    stack.auto: false #기본 cloudFormation 구성 시작 사용 x
    region:
      static: ap-northeast-2